from .settings import (
    ABILITY_PANEL_RECT,
    ARENA_RECT,
    COMBAT_PANEL_RECT,
    PANEL_GAP,
    PANEL_RADIUS,
    SIDE_PANEL_RECT,
    SIDE_PANEL_WIDTH,
    STATUS_PANEL_RECT,
    TIMER_PANEL_RECT,
    TOP_BAR_HEIGHT,
    UI_MARGIN,
)
